### ISSUE TITLE
Understand read_noise

### ISSUE THREAD

**Issue by matteobachetti** [duet-mission/duet-astro#55]
It is used in very different ways in the code, e.g.

```
bgd_rate*texp + self.read_noise**2
```
this implies its units are (ph/s)**0.5

But also
```
image + np.random.normal(loc=0,scale=read_noise,...)
```
implying ph (same as image)

I think it is important to understand its units

**Comment by bwgref** [comment]
All in image_utils?

**Comment by bwgref** [comment]
Okay. This is all fine. See the RMS notebook in #56 

For this one:

bgd_rate*texp + self.read_noise**2

bgd_rate*texp has units of counts and is the shot noise in the background (i.e. sqrt(N)**2)

read_noise is an RMS value, so it gets added in quadrature to the shot noise, which is why it's added in with a **2 here.

Second one:

image + np.random.normal(loc=0,scale=read_noise,...)

...is also correct in that this is adding Gaussian noise with sigma=RMS. I had to check this myself. In the process, I ended up re-writing the docstrings for construct_image in  #56

**Comment by matteobachetti** [comment]
Ok, right I see that I got the units wrong in the first case (it's square root of photons, not ph/s). Also, I see that the same numerical value is sometimes a number of counts (ph) or a variance (ph^2). It's annoying that apparently there is no easy way to make the units consistent -.-.
Closing for now.

**Comment by bwgref** [comment]
Re-opening this to remind us to go figure out how the read noise should actually be implemented. See the discussion in the PR comments for #56

**Comment by bwgref** [comment]
Re-closing since I think we understand this now.
